import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import '../../domain/entities/mood_entry_entity.dart';
import '../../domain/repositories/mood_repository.dart';
import '../../data/repositories/mood_repository_impl.dart';
import '../../../auth/presentation/providers/auth_provider.dart';

final moodRepositoryProvider = Provider<MoodRepository>((ref) {
  return MoodRepositoryImpl(Supabase.instance.client);
});

class MoodNotifier extends AsyncNotifier<List<MoodEntryEntity>> {
  @override
  Future<List<MoodEntryEntity>> build() async {
    // Invalida la lista si se cambia de cuenta
    ref.watch(authStateChangesProvider);
    return ref.read(moodRepositoryProvider).getMoodHistory();
  }

  Future<void> saveEntry({
    required int score,
    String? label,
    String? notes,
  }) async {
    final user = Supabase.instance.client.auth.currentUser;
    if (user == null) return;

    final entry = MoodEntryEntity(
      id: '', // Will be generated by DB
      userId: user.id,
      moodScore: score,
      moodLabel: label,
      notes: notes,
      createdAt: DateTime.now(),
    );

    state = const AsyncLoading();
    try {
      await ref.read(moodRepositoryProvider).saveMoodEntry(entry);
      // Refresh history
      ref.invalidateSelf();
      await future;
    } catch (e, st) {
      state = AsyncError(e, st);
    }
  }
}

final moodProvider = AsyncNotifierProvider<MoodNotifier, List<MoodEntryEntity>>(MoodNotifier.new);
